### ISSUE TITLE
Overlap of chat and annotation modals with footer?

### ISSUE THREAD

**Issue by lechten** [pantajoe/revealjs-plugin-social-presence#4]
In my presentations, the footer is located on top of the chat/annotate/etc. `div`s, which prevents, e.g., sending chat messages. Note that my presentations include a `div` footer with the height of the TOC progress footer to help size calculations of reveal.js.

As workaround I currently use this diff in App.jsx:

```
@@ -28,7 +28,7 @@ export default function App() {
         lecture ? (
           <>
             {!zenMode && showAnnotationHighlights && config.annotations && <AnnotationEnvironment />}
-            <div className="flex flex-col h-full">
+            <div className="flex flex-col h-5/6">
               <Controls />
               <View />
               {config.cursors && (showCursors || showOnlyGroupCursors) && !zenMode && <CursorCanvas />}
```

Is there a better way?

**Comment by pantajoe** [comment]
Sorry for answering this late, had a lot on my plate with work stuff.

Is your footer absolutely positioned? And if so, do you know the z-index? Perhaps setting a configurable z-index for the plugin or hard-coding a higher z-index is the solution.
This way, the panel doesn't have to be smaller.

**Comment by pantajoe** [comment]
I believe that my assumption is correct. When inspect the footer element in this presentation for instance https://oer.gitlab.io/OS/Operating-Systems-Scheduling.html#/slide-1, the footer has a `z-index` of 20, but the plugin has a `z-index` of 10.

Since 10 is fairly low, I increased the `z-index` properties throughout the entire plugin by 50. This should do the trick here.

**Comment by lechten** [comment]
Indeed, the z-index of the TOC progress footer is 20. Thanks!
