### ISSUE TITLE
Reset of default browser CSS padding?

### ISSUE THREAD

**Issue by lechten** [pantajoe/revealjs-plugin-social-presence#5]
Your plugin resets basic browser CSS defaults, in particular padding/indentation of items in (nested) lists. Is that on purpose?

I had to do this in my CSS:
- https://gitlab.com/oer/oer-reveal/-/commit/e3962cbee18792642eeb6a835f492ceb317b974d
- https://gitlab.com/oer/oer-reveal/-/commit/1951835109e07fdd014c1215ea06da59c63a1432

**Comment by pantajoe** [comment]
Yes, I use [`TailwindCSS`](https://tailwindcss.com), and sadly, the CSS reset is necessary for the plugin to look the same in all environments.

**Comment by lechten** [comment]
I guess that most reveal.js presentations use indented lists.

I am not familiar with TailwindCSS. Can its reset be scoped (so that it just applies to plugin elements)? If not, feel free to close this.

**Comment by pantajoe** [comment]
Hm, I see. The reset CSS cannot be scoped because the modals are directly injected into the body and they need the reset styles as well.

Does this solve this issue for you?

https://github.com/pantajoe/revealjs-plugin-social-presence/commit/e6b41a364f5d00799dd56cd824ec10fc503d10e1#diff-4c5b863268db6a3916303aa2f97909a3ac0c27b62750d3740fc0883e49397471

**Comment by lechten** [comment]
Yes, this works fine :+1:
